version: "3.8"

services:
  java-mysql:
    image: mysql
    container_name: java-mysql
    command: --default-authentication-plugin=mysql_native_password --max-allowed-packet=1024M
    tty: true
    restart: always
    environment:
      MYSQL_DATABASE: "kavaecommerce"
      MYSQL_ROOT_PASSWORD: "root"
    ports:
      - "3306:3306"
    volumes:
      - java-data:/var/lib/mysql

volumes:
  java-data: